language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- python setup.py install
script: py.test --assert=plain
env:
  matrix:
    secure: KZSyfphAHQkjmN4VVLGsd9/FOoquQd1hHlPJk4tCEeywI7zqJstP3HDPByoWBAKDfz05LDGkG65FTvQq0PkEgDzsXCf2wNOVgN2itm419zjMxRBcXJGip8o124pw/UWzFbLqJUMSwM+BNhz1H4f/MiE6BqoyxtMoUwS1OSTcuH/6/S5ZwF8b+2ObWIXHg6Bxp1HWOK9IoUTpBfR9ttADB9wlJKmpyF9ZYk22jjZ586ws74iZQEuv9Qki44G6M3Pi+OgtfOlMXaL8YSuUttw9GXl2agJK+gpBW71q0rN58c54LVrJpU7jJpFcDeUEP37WZr27pi6Ofur9/UsQI7mT7PErn7GfoaiQEAZTB4pVOjgaM18IYL7szYHW7YBqSX9mg8lDWKWUiUAXlOTTZtFQ7lAcRRTpntvbygWOyq/zLEYE/W7t9S5vpDx1d439qYCtwVEihNNZK61Nx/oCT6z+/xJcNk3BzoYLuq10eoAQR55HeXKnbD05y76SlJcgoQNlckkB47hjsdxYW2Jt09PjfQJXqwm93juuUBym9UQ1LKUEpAxeVOs6szFYiQZ9Xx8a+0fdJjFxcbw1qfnUqmSyANfQiz0LUccEZRM2HoOeBS2/DO6SmKsFDt+tsbUYyq1KoVfqnNUSA+WiBa1WAaWa9L5Zkg69ULN2fbo20X/KQWI=
